name: @name@
version: @version@
author: @author@
main: me.neznamy.tab.platforms.bukkit.BukkitTAB
api-version: 1.13
softdepend: [PlaceholderAPI, LuckPerms, LibsDisguises, ProtocolSupport, ViaVersion, floodgate]
website: "@website@"
description: @description@
commands:
  tab:
    description: Plugin's main command